name: Beta release

on:
  workflow_dispatch:
    inputs:
      force:
        description: 'force release even if no update'     
        required: false
        default: '--force-publish'

jobs:
  release-npm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.CD_PAT }}
          ref: ${{ github.ref }}

      - name: Setup node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup npm registry
        run: |
          echo "${{ secrets.NPMRC }}" > ~/.npmrc

      - name: Setup project
        run: |
          npm run setup

      - name: release npm packages to npmjs.org
        run: |
          git config --global user.name 'LongOddCode'
          git config --global user.email 'haolong@microsoft.com'
          npx lerna publish --no-private --preid beta prerelease --yes ${{ github.event.inputs.force }}

  release-vsix:
    needs: release-npm
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.CD_PAT }}
          ref: ${{ github.ref }}

      - name: Setup node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup npm registry
        run: |
          echo "${{ secrets.NPMRC }}" > ~/.npmrc

      - name: pack vsix
        working-directory: ./packages/p4
        run: |
          npm install
          npx vsce package

      - name: release VSCode extension to github
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.CD_PAT }}"
          automatic_release_tag: "latest"
          prerelease: false
          files: |
            ./packages/**/*.vsix

