name: Daily release

on:
  workflow_dispatch:
    inputs:
      bump:
        description: 'bump patch version(true or false)'
        required: false
        default: 'false'

jobs:

  daily-release-npm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.CD_PAT }}
          ref: master

      - name: Setup node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14

      - name: Setup npm registry
        run: |
          echo "${{ secrets.NPMRC }}" > ~/.npmrc

      - name: Setup project
        run: |
          npm run setup

      - name: Setup git
        run: |
          git config --global user.name 'LongOddCode'
          git config --global user.email 'haolong@microsoft.com'
          echo ${{ github.event.name }} 


      - name: release npm packages to npmjs.org
        if: ${{ github.event.inputs.bump == 'false' }} 
        run: |
          echo ${{ github.event.inputs.bump }}
          npx lerna publish --no-private --preid=alpha --dist-tag=alpha --yes prerelease

      - name: bump patch version and release npm packages to npmjs.org
        if: ${{ github.event.inputs.bump == 'true' }}
        run: |
          echo ${{ github.event.inputs.bump }}
          npx lerna publish --no-private --preid=alpha --dist-tag=alpha --yes prepatch --force-publish

      - name: pack vsix
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 5
          retry_on: error
          command: |
            cd ./packages/p4
            npm install
            npx vsce package

      - name: release VSCode extension to github
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.CD_PAT }}"
          automatic_release_tag: "daily"
          prerelease: true
          files: |
            ./packages/**/*.vsix
