name: Daily release

on:
  push:
    branches:
      - "master"

jobs:
  daily-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.CD_PAT }}

      - name: Setup node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup npm registry
        run: |
          echo "${{ secrets.NPMRC }}" > ~/.npmrc

      - name: Setup project
        run: |
          npm run setup

      - name: release npm packages to npmjs.org
        run: |
          git config --global user.name 'LongOddCode'
          git config --global user.email 'haolong@microsoft.com'
          npx lerna publish --no-private --yes prerelease
