name: E2E Test

on:
  workflow_dispatch:

jobs:
  run-e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: check git log 
        id: git-log
        shell: bash
        run: |
          mapfile -t assignees< <(git log --pretty="%an" e2e..HEAD | tee | sort | uniq | tr '\n' ',')
          assignees=${assignees::-1}
          echo $assignees
          assignees="yiqing"
          echo "::set-output name=assignees::$assignees"
          git_log=$(git log --pretty="%h %ad - %s (%an)" e2e..HEAD  | tee | tr -d '\n')
          mapfile -t git_log< <( git log --pretty="%h %ad - %s (%an)" e2e..HEAD | tee)
          echo "::set-output name=log::${git_log[@]}"
      - name: fail
        run: |
          exit 1

      - name: create azure devops issue if tests failed
        id: create-issue
        uses: stefanstranger/azuredevops-bug-action@1.1
        if: failure()
        with:
          OrganizationName: "msazure"
          PAT: ${{ secrets.ADO_PAT }}
          ProjectName: "Microsoft Teams Extensibility"
          AreaPath: "Microsoft Teams Extensibility\\Teams Extensibility E2E Team"
          IterationPath: "Microsoft Teams Extensibility"
          GithubToken: ${{ secrets.CD_PAT }}
          WorkflowFileName: "e2e-test.yml"
        env:
          PAT: ${{ secrets.ADO_PAT }}
          GithubToken: ${{ secrets.CD_PAT }}
        
