name: E2E Test

on:
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: windows-latest
    steps:
      - name: fail
        run: |
          exit 1

  create-ado-issue:
    runs-on: ubuntu-latest
    needs: run-tests
    if: failure()
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: check git log 
        id: git-log
        shell: bash
        run: |
          git_log=$(git log --pretty="<tr> <td>%h</td> <td>%ad</td> <td>%s</td> <td><a href=\"#\" data-vss-mention=\"version:2.0\">(%ae) &#127867;</a></td> </tr>" e2e..HEAD | grep -v "noreply" | tee | tr -d '\n')
          echo $git_log
          echo "::set-output name=log::${git_log[@]}"

      - name: create azure devops issue if test is failed
        uses: azure/CLI@v1
        with:
          azcliversion: 2.25.0
          inlineScript: |
           read -r -d '' description << EOM
<html>
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<body>
<div class="w3-container">
<table class="w3-table w3-striped">
  <tr>
    <th>Hash</th>
    <th>Time</th>
    <th>Message</th>
    <th>author</th>
  </tr>
  ${{ steps.git-log.outputs.log }}
</table>
</div>
</body>
</html>
EOM 
            export AZURE_DEVOPS_EXT_PAT=${{ secrets.ADO_PAT }}
            az extension add --name azure-devops
            az boards work-item create --title="long's test" \
                             --type=Bug \
                             --area="Microsoft Teams Extensibility\Teams Extensibility E2E Team" \
                             --assigned-to="haolong@microsoft.com" \
                             --iteration="Microsoft Teams Extensibility" \
                             --organization="https://msazure.visualstudio.com/" \
                             --project="Microsoft Teams Extensibility" \
                             --description=$description
