name: E2E Test

on:
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: fail
        run: |
          exit 1

      - name: tag
        if: success()
        run: |
          git tag -f e2e HEAD
          git push origin -f e2e

  create-ado-issue:
    runs-on: ubuntu-latest
    needs: run-tests
    if: failure()
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: check git log 
        id: git-log
        shell: bash
        run: |
          git_log=$(git log --pretty="<tr> <td>%h</td> <td>%ad</td> <td>%s</td> <td><a href=\"#\" data-vss-mention=\"version:2.0,haolong@microsoft.com\">haolong@microsoft.com</a></td> </tr>" e2e..HEAD | grep -v "noreply" | tee | tr -d '\n')
          echo $git_log
          echo "::set-output name=log::${git_log[@]}"

      - name: create azure devops issue if test is failed
        uses: azure/CLI@v1
        with:
          azcliversion: 2.25.0
          inlineScript: |
            export AZURE_DEVOPS_EXT_PAT=${{ secrets.ADO_PAT }}
            az extension add --name azure-devops
            az boards work-item create --title="E2E tests failed" \
                             --type=Task \
                             --area="demo" \
                             --assigned-to="haolong@microsoft.com" \
                             --iteration="demo" \
                             --organization="https://dev.azure.com/haolong0010/" \
                             --project="demo" \
                             --description="<table class=\"w3-table w3-striped w3-bordered\"><tr><th>Hash</th> <th>Time</th> <th>Message</th> <th>author</th> </tr>${{ steps.git-log.outputs.log }}</table>"
