name: E2E Test

on:
  workflow_dispatch:

jobs:
  run-e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: check git log 
        id: git-log
        shell: bash
        run: |
          mapfile -t assignees< <(git log --pretty="%an" e2e..HEAD | tee | sort | uniq | tr '\n' ',')
          assignees=${assignees::-1}
          echo $assignees
          assignees="yiqing"
          echo "::set-output name=assignees::$assignees"
          git_log=$(git log --pretty="%h %ad - %s (%an)" e2e..HEAD  | tee | tr -d '\n')
          mapfile -t git_log< <( git log --pretty="%h %ad - %s (%an)" e2e..HEAD | tee)
          echo "::set-output name=log::${git_log[@]}"

      - name: fail
        run: |
          exit 1

      - name: Azure CLI script
        if: failure()
        uses: azure/CLI@v1
        with:
          azcliversion: 2.25.0
          inlineScript: |
            export AZURE_DEVOPS_EXT_PAT=${{ secrets.ADO_PAT }}
            az config set extension.use_dynamic_install=yes_without_prompt
            az boards work-item create --title="long's test" \
                                       --type=Bug \
                                       --area="Microsoft Teams Extensibility\Teams Extensibility E2E Team" \
                                       --assigned-to="haolong@microsoft.com" \
                                       --iteration="Microsoft Teams Extensibility" \
                                       --organization="https://msazure.visualstudio.com/" \
                                       --project="Microsoft Teams Extensibility" \ 
                                       --description="The Workflow failed"
