name: E2E Test

on:
  workflow_dispatch:

jobs:
  run-e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYYMMDD-HH
          utcOffset: "+08:00"

      - name: check git log 
        id: git-log
        shell: bash
        run: |
          mapfile -t assignees< <(git log --pretty="%an" e2e..HEAD | tee | sort | uniq)
          echo "::set-output name=assignees::$assignees"
          git_log=""
          echo "::set-output name=log::$git_log"

      - uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.CD_PAT }}
          RUN_URL: https://github.com/LongOddCode/lerna-test/actions/runs/${{ github.run_id }}
          LOG: ${{ steps.list-assignees.outputs.assignees }}
        with:
          assignees: ${{ steps.list-assignees.outputs.assignees }}
          update_existing: true
          filename: .github/ISSUE_TEMPLATE/e2e-test.md
