name: E2E Test

on:
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: windows-latest
    steps:
      - name: fail
        run: |
          exit 1

  create-ado-issue:
    runs-on: ubuntu-latest
    needs: run-tests
    if: ${{ failure() && github.ref == "refs/heads/dev" }}
    steps:
      - name: fail
        run: |
          echo ${{ github.ref }}
          exit 0
