name: E2E Test

on:
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: fail
        run: |
          exit 1

      - name: tag
        if: success()
        run: |
          git tag -f e2e HEAD
          git push origin -f e2e

  create-ado-issue:
    runs-on: ubuntu-latest
    needs: run-tests
    if: failure()
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: check git log 
        id: git-log
        shell: bash
        run: |

          declare -A email_uid
          for i in $(git log --pretty="%ae"  e2e..HEAD | sort | uniq);
          do
            if [ ${email_uid[$i]+exist} ]; then
              continue
            fi

            resp=$(curl -u :rwcvvakek7docvdp4c6y4nijhwbockokapr7a6mzxxdrg52zcpqa  "https://vssps.dev.azure.com/msazure/_apis/identities?searchFilter=General&filterValue=$i&queryMembership=None&api-version=6.0")

            uid=$(echo $resp | jq '.value | .[] | .id' | xargs echo)
            email_uid[$i]=$uid
          done
          echo ${email_uid[@]}

          gitlog=$(git log --pretty=format:'{"commit":"%h","subject":"%s","email":"%aE","date":"%aD"},' e2e..HEAD | grep -v "noreply")
          gitlog=[${gitlog::-1}] 

          description="<tr> <th>Commit</th> <th>Date</th> <th>Subject</th> <th>Author</th> </tr>"
          for row in $(echo $gitlog | jq -r '.[] | @base64'); do
            _jq() {
              echo ${row} | base64 --decode | jq -r ${1}
            }
            description="$description <tr> <td>$(_jq '.commit')</td> <td>$(_jq '.subject')</td> <td>$(_jq '.date')</td> <td><a href=\"#\" data-vss-mention=\"version:2.0,${email_uid[$(_jq '.email')]}\">$(_jq '.email')</a></td> </tr> "
          done
          echo $description
          echo "::set-output name=description::$description"

      - name: create azure devops issue if test is failed
        uses: azure/CLI@v1
        with:
          azcliversion: 2.25.0
          inlineScript: |
            export AZURE_DEVOPS_EXT_PAT=${{ secrets.ADO_PAT }}
            az config set extension.use_dynamic_install=yes_without_prompt
            az boards work-item create --title="E2E tests failed" \
                             --type=Task \
                             --area="demo" \
                             --assigned-to="haolong@microsoft.com" \
                             --iteration="demo" \
                             --organization="https://dev.azure.com/haolong0010/" \
                             --project="demo" \
                             --description="<table class=\"w3-table w3-striped w3-bordered\">${{ steps.git-log.outputs.description }}</table>"
