name: E2E Test

on:
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: windows-latest
    steps:
      - name: fail
        run: |
          exit 0

  create-ado-issue:
    runs-on: ubuntu-latest
    needs: run-tests
    if: failure()
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: check git log 
        id: git-log
        shell: bash
        run: |
          git_log=$(git log --pretty="<div>%h %ad - %s <a href=\"#\" data-vss-mention=\"version:2.0\">(%ae) &#127867;</a>&nbsp;</div>" e2e..HEAD  | tee | tr -d '\n')
          echo $git_log
          echo "::set-output name=log::${git_log[@]}"

      - name: create azure devops issue if test is failed
        uses: azure/CLI@v1
        with:
          azcliversion: 2.25.0
          inlineScript: |
            export AZURE_DEVOPS_EXT_PAT=${{ secrets.ADO_PAT }}
            az extension add --name azure-devops
            az boards work-item create --title="long's test" \
                             --type=Bug \
                             --area="Microsoft Teams Extensibility\Teams Extensibility E2E Team" \
                             --assigned-to="haolong@microsoft.com" \
                             --iteration="Microsoft Teams Extensibility" \
                             --organization="https://msazure.visualstudio.com/" \
                             --project="Microsoft Teams Extensibility" \
                             --description="${{ steps.git-log.outputs.log }}"
