name: E2E Test

on:
  workflow_dispatch:

jobs:
  run-e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYYMMDD-HH
          utcOffset: "+08:00"

      - name: check git log 
        id: git-log
        shell: bash
        run: |
          mapfile -t assignees< <(git log --pretty="%an" e2e..HEAD | tee | sort | uniq | tr '\n' ',')
          assignees=${assignees::-1}
          echo "::set-output name=assignees::$assignees"
          echo $assignees
          assignees="yiqing-zhao"
          git_log=$(git log --pretty="%h %ad - %s (%an)" e2e..HEAD  | tee | tr -d '\n')
          mapfile -t git_log< <( git log --pretty="%h %ad - %s (%an)" e2e..HEAD | tee)
          echo "::set-output name=log::${git_log[@]}"

      - name: create issue if tests failed
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.CD_PAT }}
          RUN_URL: https://github.com/LongOddCode/lerna-test/actions/runs/${{ github.run_id }}
          LOG: ${{ steps.git-log.outputs.log }}
        with:
          assignees: ${{ steps.git-log.outputs.assignees }}
          update_existing: true
          filename: .github/ISSUE_TEMPLATE/e2e-test.md
