name: mail

on:
  workflow_dispatch:
    inputs:
      run_id:
        description: "run id"
        required: true
        type: string

jobs:
  mail:
    runs-on: ubuntu-latest
    steps:
      - name: check
        run: |
          run=`curl \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.event.inputs.run_id }}`

          status=`jq -r '.conclusion' <<< "$run"`
          run_attempt=`jq -r '.run_attempt' <<< "$run"`
          echo $status
          echo $run_attempt
