name: os

on:
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14

      - name: lerna
        run: |
          npm install
          npx lerna bootstrap

      - name: Azure Login
        run: |
          ls -alh ~/.local
          ls -alh ~/.local/share
          ls -alh ~/.local/share/keyrings
          echo 'Default_keyring' >> ~/.local/share/keyrings/default
          echo '${{ secrets.DEFAULT_KEYRING }}' >> ~/.local/share/keyrings/Default_keyring.keyring

          npx ts-node packages/p1/azureLogin.ts -- '${{ secrets.AZURE_USERNAME  }}' '${{ secrets.AZURE_PASSWORD }}'
