name: os

on:
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    env:
      AZURE_USERNAME: ${{ secrets.AZURE_USERNAME }}
      AZURE_PASSWORD: ${{ secrets.AZURE_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14

      - name: Install function core tool in Linux
        run: |
          curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
          sudo mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg
          sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-$(lsb_release -cs)-prod $(lsb_release -cs) main" > /etc/apt/sources.list.d/dotnetdev.list'
          sudo apt-get update
          sudo apt-get install azure-functions-core-tools-3
          sudo apt-get install libsecret-1-dev
          sudo apt install gnome-keyring --no-install-recommends
          sudo apt install dbus-x11 gnupg2 pass
          export $(dbus-launch)
          export DISPLAY=:0.0

      - name: Azure Login
        run: |
          npm install
          npx lerna bootstrap
          npx ts-node packages/p1/azureLogin.ts -- '${{ env.AZURE_USERNAME }}' '${{ env.AZURE_PASSWORD }}'
