name: os

on:
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    env:
      AZURE_USERNAME: ${{ secrets.AZURE_USERNAME }}
      AZURE_PASSWORD: ${{ secrets.AZURE_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14

      - name: lerna
        run: |
          npm install
          npx lerna bootstrap

      - name: Azure Login
        run: |
          mkdir -p ~/.local/share/keyrings
          echo "Default_keyring" >> ~/.local/share/keyrings/default

          npx ts-node packages/p1/azureLogin.ts -- '${{ env.AZURE_USERNAME }}' '${{ env.AZURE_PASSWORD }}'
