name: reviewer

on:
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14

      - name: assign-reviewer
        uses: LongOddCode/assign-reviewer@0.1.0
        with:
          reviewers: '["chagong"]'
          conscript: 0
          script: bash
          result: TELEMETRY_RESULT
          run: |
            line=`git diff -U0 ${{ github.base_ref }} | grep '^[+-]' | grep -Ev '^(--- a/|\+\+\+ b/)' | grep -i "telemetry" | wc -l`
            if [ $line -gt 0 ]; then
              echo '::set-output name=TELEMETRY_RESULT::true'
            fi
