name: test

on:
  workflow_dispatch:

jobs:
  map:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - name: exit 1
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          exit 1

      - name: exit 0
        run: |
          exit 0

  reduce:
    needs: map
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: done
        run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/mail/dispatches \
            -d '{"ref":"${GITHUB_REF##*/}","inputs":{"run_id":"${{ github.run_id }}"}}'
