name: test

on:
  workflow_dispatch:
    inputs:
      parent_id:
        description: "trigger workflow id"
        required: false

jobs:
  do-sth:
    runs-on: ubuntu-latest
    steps:
      - name: echo github
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"

      - name: echo job
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: |
          echo "$JOB_CONTEXT"
