name: test

on:
  workflow_dispatch:

jobs:
  map:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - name: exit 1
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          exit 1

      - name: exit 0
        run: |
          exit 0

  reduce:
    needs: map
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: rerun
        if: ${{ github.run_attempt < 4 }}
        run: |
          jobs=`curl \
            -u :${{ secrets.GITHUB_TOKEN }} \
            https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/attempts/${{ github.run_attempt }}/jobs?per_page=100`

          cases=`echo $jobs| jq -r '.jobs[] | select(.conclusion=="failure") | .id'`

          while IFS= read -r case;
          do
            curl \
                -X POST \
                -u :${{ secrets.GITHUB_TOKEN }} \
                -H "Accept: application/vnd.github.v3+json" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/repos/${{ github.repository }}/actions/jobs/$case/rerun
          done <<< $cases

      - name: done
        if: ${{ github.run_attempt >= 4 }}
        run: |
          echo 1
