name: test

on:
  workflow_dispatch:
  pull_request:

jobs:
  setup:
    runs-on: ubuntu-latest
    if: github.actor == 'deps'
    steps:
      - name: do sth.
        run: |
          echo "do sth."
