name: test

on:
  workflow_dispatch:
    inputs:
      parent_id:
        description: "trigger workflow id"
        required: false

jobs:
  do-sth:
    runs-on: ubuntu-latest
    steps:
      - name: echo sth
        run: |
          echo ${{ job.id }}
