name: test

on:
  workflow_dispatch:

jobs:
  do-sth:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - name: echo github
        if: ${{ GITHUB_REF_NAME == "main" }}
        run: |
          echo $GITHUB_REF_NAME
