name: test

on:
  workflow_dispatch:
    parant_id:
      descripton: "trigger workflow id"
      required: false

jobs:
  do-sth:
    runs-on: ubuntu-latest
    steps:
      - name: echo sth
        run: |
          echo "hello world"
