name: test

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: do sth.
        run: |
          echo "do sth."

  execute-case:
    needs: setup
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - name: exit 1
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          exit 1

      - name: exit 0
        run: |
          exit 0

  tear-down:
    if: ${{ always() }}
    needs: execute-case
    runs-on: ubuntu-latest
    steps:
      - name: do sth.
        run: |
          echo "do sth."

  rerun:
    needs: tear-down
    if: ${{ failure() && github.run_attempt < 3 }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: |
          curl \
           -X POST \
           -H "Accept: application/vnd.github+json" \
           -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
           -H "X-GitHub-Api-Version: 2022-11-28" \
           https://api.github.com/repos/${{ github.repository }}/actions/workflows/rerun.yml/dispatches \
           -d '{"ref":"'${GITHUB_REF##*/}'","inputs":{"run_id":"${{ github.run_id }}", "max_attempts":"3"}}'

  report:
    needs: execute-case
    if: ${{ success() || (failure() && github.run_attempt >=3) }}
    runs-on: ubuntu-latest
    steps:
      - name: do sth.
        run: |
          echo "do sth."
